version: '3'
services:
  backend:
    container_name: backend-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      PORT: 5000
    depends_on:
      - database
    volumes:
      - mongo-volume:/backend
  client:
    container_name: client-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    environment:
      PORT: 5001
    depends_on:
      - database
    volumes:
      - mongo-volume:/client
  database:
    container_name: yolomy-database
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
volumes:
  mongo-volume: