version: '3.6'

services:
  backend-server:
    container_name: backend-server
    depends_on:
      - mongo
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      MONGODB_URI: 'mongodb://172.20.0.1/yolomy'
    networks:
      backend-network:
        ipv4_address: 172.20.0.2
  mongo:
    container_name: backend-database
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: yolomy
    networks:
      backend-network:
        ipv4_address: 172.20.0.3
  yolomy:
    container_name: frontend-client
    stdin_open: true
    depends_on:
      - mongo
      - backend-server
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    networks:
      backend-network:
        ipv4_address: 172.20.0.4

volumes:
  database:


networks:
  backend-network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16